/*
 * This file is generated by jOOQ.
 */
package dev.babatunde.transferservice.repository.jooq;


import dev.babatunde.transferservice.repository.jooq.tables.Transactions;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IDX_TRANS_ACCOUNT_ID = Internal.createIndex(DSL.name("idx_trans_account_id"), Transactions.TRANSACTIONS, new OrderField[] { Transactions.TRANSACTIONS.ACCOUNT_ID }, false);
    public static final Index IDX_TRANS_REFERENCE = Internal.createIndex(DSL.name("idx_trans_reference"), Transactions.TRANSACTIONS, new OrderField[] { Transactions.TRANSACTIONS.PAYMENT_REFERENCE }, false);
    public static final Index IDX_TRANS_STATUS = Internal.createIndex(DSL.name("idx_trans_status"), Transactions.TRANSACTIONS, new OrderField[] { Transactions.TRANSACTIONS.STATUS }, false);
}
