/*
 * This file is generated by jOOQ.
 */
package dev.babatunde.transferservice.repository.jooq;


import dev.babatunde.transferservice.repository.jooq.tables.Accounts;
import dev.babatunde.transferservice.repository.jooq.tables.TransactionEntries;
import dev.babatunde.transferservice.repository.jooq.tables.Transactions;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.accounts</code>.
     */
    public final Accounts ACCOUNTS = Accounts.ACCOUNTS;

    /**
     * The table <code>public.transaction_entries</code>.
     */
    public final TransactionEntries TRANSACTION_ENTRIES = TransactionEntries.TRANSACTION_ENTRIES;

    /**
     * The table <code>public.transactions</code>.
     */
    public final Transactions TRANSACTIONS = Transactions.TRANSACTIONS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Accounts.ACCOUNTS,
            TransactionEntries.TRANSACTION_ENTRIES,
            Transactions.TRANSACTIONS
        );
    }
}
