/*
 * This file is generated by jOOQ.
 */
package dev.babatunde.transferservice.repository.jooq;


import dev.babatunde.transferservice.repository.jooq.tables.Accounts;
import dev.babatunde.transferservice.repository.jooq.tables.TransactionEntries;
import dev.babatunde.transferservice.repository.jooq.tables.Transactions;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.accounts</code>.
     */
    public static final Accounts ACCOUNTS = Accounts.ACCOUNTS;

    /**
     * The table <code>public.transaction_entries</code>.
     */
    public static final TransactionEntries TRANSACTION_ENTRIES = TransactionEntries.TRANSACTION_ENTRIES;

    /**
     * The table <code>public.transactions</code>.
     */
    public static final Transactions TRANSACTIONS = Transactions.TRANSACTIONS;
}
