/*
 * This file is generated by jOOQ.
 */
package dev.babatunde.transferservice.repository.jooq.tables.records;


import dev.babatunde.transferservice.repository.jooq.tables.TransactionEntries;

import java.math.BigDecimal;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TransactionEntriesRecord extends UpdatableRecordImpl<TransactionEntriesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.transaction_entries.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.transaction_entries.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.transaction_entries.account_id</code>.
     */
    public void setAccountId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.transaction_entries.account_id</code>.
     */
    public UUID getAccountId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.transaction_entries.type</code>.
     */
    public void setType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.transaction_entries.type</code>.
     */
    public String getType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.transaction_entries.amount</code>.
     */
    public void setAmount(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.transaction_entries.amount</code>.
     */
    public BigDecimal getAmount() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>public.transaction_entries.transaction_id</code>.
     */
    public void setTransactionId(UUID value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.transaction_entries.transaction_id</code>.
     */
    public UUID getTransactionId() {
        return (UUID) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TransactionEntriesRecord
     */
    public TransactionEntriesRecord() {
        super(TransactionEntries.TRANSACTION_ENTRIES);
    }

    /**
     * Create a detached, initialised TransactionEntriesRecord
     */
    public TransactionEntriesRecord(UUID id, UUID accountId, String type, BigDecimal amount, UUID transactionId) {
        super(TransactionEntries.TRANSACTION_ENTRIES);

        setId(id);
        setAccountId(accountId);
        setType(type);
        setAmount(amount);
        setTransactionId(transactionId);
        resetChangedOnNotNull();
    }
}
